version: '3.3'

services:
  web:
    image: php:7.2
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
      - core_db
    container_name: ${PROJECTNAME}_web
    volumes:
      - ../code:/var/www/html
      - ../data/uploads:/var/www/html/uploads
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ../data/logs/error.log:/var/www/error.log
      - ../data/logs/access.log:/var/www/access.log
    environment:
      VIRTUAL_HOST: ${PRD_HOST}, www.${PRD_HOST}
      LETSENCRYPT_HOST: ${PRD_HOST}
      LETSENCRYPT_EMAIL: ${PRD_SSL}
    restart: always

networks:
    default:
      external:
        name: ${PRD_NET}
